apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: preproc-train-analyze-deploy-
spec:
  entrypoint: preproc-train-analyze-deploy
  arguments:
    parameters:
      - name: input-handle-eval
      - name: input-handle-train
      - name: outfile-prefix-eval
      - name: outfile-prefix-train
      - name: train-steps
        value: 10000
      - name: project
      - name: working-dir
      - name: tft-setup-file
        value: "/ml/transform/setup.py"
      - name: tfma-setup-file
        value: "/ml/analysis/setup.py"
      - name: preprocess-mode
        value: local
      - name: preprocessing-module
        value: ''
      - name: tfma-mode
        value: local
      - name: workers
        value: 0
      - name: pss
        value: 0
      - name: max-rows
        value: 10000
      - name: ts1-1
      - name: ts2-1
      - name: ts1-2
      - name: ts2-2
  templates:
  - name: preproc-train-analyze-deploy
    inputs:
      parameters:
      - name: input-handle-eval
      - name: input-handle-train
      - name: outfile-prefix-eval
      - name: outfile-prefix-train
      - name: project
      - name: preprocess-mode
      - name: preprocessing-module
      - name: tfma-mode
      - name: train-steps
      - name: working-dir
      - name: tft-setup-file
      - name: tfma-setup-file
      - name: workers
      - name: pss
      - name: max-rows
      - name: ts1-1
      - name: ts2-1
      - name: ts1-2
      - name: ts2-2
    dag:
      tasks:
      - name: preprocesseval
        template: preprocess
        arguments:
          parameters:
          - name: input-handle
            value: "{{inputs.parameters.input-handle-eval}}"
          - name: outfile-prefix
            value: "{{inputs.parameters.outfile-prefix-eval}}"
          - name: working-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-eval"
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: setup-file
            value: "{{inputs.parameters.tft-setup-file}}"
          - name: preprocess-mode
            value: "{{inputs.parameters.preprocess-mode}}"
          - name: max-rows
            value: 5000
          - name: stage
            value: eval
          - name: ts1
            value: "{{inputs.parameters.ts1-1}}"
          - name: ts2
            value: "{{inputs.parameters.ts2-1}}"
          - name: preprocessing-module
            value: "{{inputs.parameters.preprocessing-module}}"
      - name: preprocesstrain
        template: preprocess
        arguments:
          parameters:
          - name: input-handle
            value: "{{inputs.parameters.input-handle-train}}"
          - name: outfile-prefix
            value: "{{inputs.parameters.outfile-prefix-train}}"
          - name: working-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-train"
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: setup-file
            value: "{{inputs.parameters.tft-setup-file}}"
          - name: preprocess-mode
            value: "{{inputs.parameters.preprocess-mode}}"
          - name: max-rows
            value: "{{inputs.parameters.max-rows}}"
          - name: stage
            value: train
          - name: ts1
            value: "{{inputs.parameters.ts1-1}}"
          - name: ts2
            value: "{{inputs.parameters.ts2-1}}"
          - name: preprocessing-module
            value: "{{inputs.parameters.preprocessing-module}}"
      - name: preprocesseval2
        template: preprocess
        arguments:
          parameters:
          - name: input-handle
            value: "{{inputs.parameters.input-handle-eval}}"
          - name: outfile-prefix
            value: "{{inputs.parameters.outfile-prefix-eval}}"
          - name: working-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-eval2"
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: setup-file
            value: "{{inputs.parameters.tft-setup-file}}"
          - name: preprocess-mode
            value: "{{inputs.parameters.preprocess-mode}}"
          - name: max-rows
            value: 5000
          - name: stage
            value: eval
          - name: ts1
            value: "{{inputs.parameters.ts1-2}}"
          - name: ts2
            value: "{{inputs.parameters.ts2-2}}"
          - name: preprocessing-module
            value: "{{inputs.parameters.preprocessing-module}}"
      - name: preprocesstrain2
        template: preprocess
        arguments:
          parameters:
          - name: input-handle
            value: "{{inputs.parameters.input-handle-train}}"
          - name: outfile-prefix
            value: "{{inputs.parameters.outfile-prefix-train}}"
          - name: working-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-train2"
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: setup-file
            value: "{{inputs.parameters.tft-setup-file}}"
          - name: preprocess-mode
            value: "{{inputs.parameters.preprocess-mode}}"
          - name: max-rows
            value: "{{inputs.parameters.max-rows}}"
          - name: stage
            value: train
          - name: ts1
            value: "{{inputs.parameters.ts1-2}}"
          - name: ts2
            value: "{{inputs.parameters.ts2-2}}"
          - name: preprocessing-module
            value: "{{inputs.parameters.preprocessing-module}}"
      - name: train
        dependencies: [preprocesseval, preprocesstrain]
        template: train
        arguments:
          parameters:
          - name: tf-transform-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-train"
          - name: output-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf"
          - name: job-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf"
          - name: train-files-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-train"
          - name: eval-files-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-eval"
          - name: train-files-prefix
            value: "{{inputs.parameters.outfile-prefix-train}}"
          - name: eval-files-prefix
            value: "{{inputs.parameters.outfile-prefix-eval}}"
          - name: train-steps
            value: "{{inputs.parameters.train-steps}}"
          - name: workers
            value: "{{inputs.parameters.workers}}"
          - name: pss
            value: "{{inputs.parameters.pss}}"
          - name: working-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf/serving_model_dir"
      - name: train2
        dependencies: [preprocesseval2, preprocesstrain2]
        template: train
        arguments:
          parameters:
          - name: tf-transform-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-train2"
          - name: output-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf2"
          - name: job-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf2"
          - name: train-files-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-train2"
          - name: eval-files-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-eval2"
          - name: train-files-prefix
            value: "{{inputs.parameters.outfile-prefix-train}}"
          - name: eval-files-prefix
            value: "{{inputs.parameters.outfile-prefix-eval}}"
          - name: train-steps
            value: "{{inputs.parameters.train-steps}}"
          - name: workers
            value: "{{inputs.parameters.workers}}"
          - name: pss
            value: "{{inputs.parameters.pss}}"
          - name: working-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf2/serving_model_dir"
      - name: analyze
        dependencies: [preprocesseval, train]
        template: analyze
        arguments:
          parameters:
          - name: input-csv
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-eval/eval.csv-00000-of-00001"
          - name: tfma-run-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tfma/output"
          - name: eval-model-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf/eval_model_dir"
          - name: tfma-mode
            value: "{{inputs.parameters.tfma-mode}}"
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: setup-file
            value: "{{inputs.parameters.tfma-setup-file}}"
      - name: analyze2
        dependencies: [preprocesseval, train2]
        template: analyze
        arguments:
          parameters:
          - name: input-csv
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tft-eval/eval.csv-00000-of-00001"
          - name: tfma-run-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tfma2/output"
          - name: eval-model-dir
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf2/eval_model_dir"
          - name: tfma-mode
            value: "{{inputs.parameters.tfma-mode}}"
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: setup-file
            value: "{{inputs.parameters.tfma-setup-file}}"
      - name: cmle-op
        dependencies: [train]
        template: cmleop
        arguments:
          parameters:
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: version-name
            value: "{{workflow.name}}"
          - name: gcs-path
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf/serving_model_dir/export/chicago-taxi"
      - name: cmle-op2
        dependencies: [train2]
        template: cmleop
        arguments:
          parameters:
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: version-name
            value: "{{workflow.name}}_2"
          - name: gcs-path
            value: "{{inputs.parameters.working-dir}}/{{workflow.name}}/tf2/serving_model_dir/export/chicago-taxi"
  - name: preprocess
    inputs:
      parameters:
      - name: input-handle
      - name: working-dir
      - name: setup-file
      - name: outfile-prefix
      - name: project
      - name: preprocess-mode
      - name: stage
      - name: max-rows
      - name: ts1
      - name: ts2
      - name: preprocessing-module
    container:
      image: gcr.io/google-samples/ml-pipeline-dataflow-tftbq-taxi
      args: [
          "--input_handle", "{{inputs.parameters.input-handle}}",
          "--outfile_prefix", "{{inputs.parameters.outfile-prefix}}",
          "--working_dir", "{{inputs.parameters.working-dir}}",
          "--project", "{{inputs.parameters.project}}",
          "--mode", "{{inputs.parameters.preprocess-mode}}",
          "--setup_file", "{{inputs.parameters.setup-file}}",
          "--max_rows", "{{inputs.parameters.max-rows}}",
          "--ts1", "{{inputs.parameters.ts1}}",
          "--ts2", "{{inputs.parameters.ts2}}",
          "--stage", "{{inputs.parameters.stage}}",
          "--preprocessing_module", "{{inputs.parameters.preprocessing-module}}",
      ]
  - name: train
    inputs:
      parameters:
      - name: tf-transform-dir
      - name: working-dir
      - name: output-dir
      - name: job-dir
      - name: train-files-dir
      - name: eval-files-dir
      - name: train-files-prefix
      - name: eval-files-prefix
      - name: train-steps
      - name: pss
      - name: workers
    container:
      image: gcr.io/google-samples/ml-pipeline-kubeflow-tf-taxi
      args: [
          "--tf-transform-dir", "{{inputs.parameters.tf-transform-dir}}",
          "--output-dir", "{{inputs.parameters.output-dir}}",
          "--working-dir", "{{inputs.parameters.working-dir}}",
          "--job-dir", "{{inputs.parameters.job-dir}}",
          "--train-files-dir", "{{inputs.parameters.train-files-dir}}",
          "--eval-files-dir", "{{inputs.parameters.eval-files-dir}}",
          "--train-files-prefix", "{{inputs.parameters.train-files-prefix}}",
          "--eval-files-prefix", "{{inputs.parameters.eval-files-prefix}}",
          "--train-steps", "{{inputs.parameters.train-steps}}",
          "--workers", "{{inputs.parameters.workers}}",
          "--pss", "{{inputs.parameters.pss}}",
      ]
  - name: analyze
    inputs:
      parameters:
      - name: project
      - name: input-csv
      - name: tfma-run-dir
      - name: eval-model-dir
      - name: tfma-mode
      - name: setup-file
    container:
      image: gcr.io/google-samples/ml-pipeline-dataflow-tfma-taxi
      args: [
          "--input_csv", "{{inputs.parameters.input-csv}}",
          "--tfma_run_dir", "{{inputs.parameters.tfma-run-dir}}",
          "--eval_model_dir", "{{inputs.parameters.eval-model-dir}}",
          "--mode", "{{inputs.parameters.tfma-mode}}",
          "--setup_file", "{{inputs.parameters.setup-file}}",
          "--project", "{{inputs.parameters.project}}",
      ]
  - name: cmleop
    inputs:
      parameters:
      - name: project
      - name: version-name
      - name: gcs-path
    container:
      image: gcr.io/google-samples/ml-pipeline-cmle-op
      args: [
          "--project", "{{inputs.parameters.project}}",
          "--gcs-path", "{{inputs.parameters.gcs-path}}",
          "--version-name", "{{inputs.parameters.version-name}}",
      ]
