apiVersion: "kubeflow.org/v1alpha1"
kind: "TFJob"
metadata:
  name: "tf-job"
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: gcr.io/google-samples/ml-pipeline-kubeflow-trainer-taxi
              name: tensorflow
              command:
                - python
                - -m
                - trainer.task
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: gcr.io/google-samples/ml-pipeline-kubeflow-trainer-taxi
              name: tensorflow
              command:
                - python
                - -m
                - trainer.task
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: PS
      template:
        spec:
          containers:
            - image: gcr.io/google-samples/ml-pipeline-kubeflow-trainer-taxi
              name: tensorflow
              command:
                - python
                - -m
                - trainer.task
          restartPolicy: OnFailure