# Copyright 2021 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM pytorch/pytorch:1.8.1-cuda10.2-cudnn7-runtime

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install gcsfs
RUN pip3 install google-cloud-storage

RUN apt-get update -y
RUN apt-get install --no-install-recommends -y -q ca-certificates wget unzip


RUN wget -nv https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip && \
    unzip -qq google-cloud-sdk.zip -d tools && \
    rm google-cloud-sdk.zip && \
    tools/google-cloud-sdk/install.sh --usage-reporting=false \
        --path-update=false --bash-completion=false \
        --disable-installation-options && \
    tools/google-cloud-sdk/bin/gcloud -q components update \
        gcloud core gsutil && \
    tools/google-cloud-sdk/bin/gcloud -q components install kubectl && \
    tools/google-cloud-sdk/bin/gcloud config set component_manager/disable_update_check true


ENV PATH $PATH:/tools/google-cloud-sdk/bin

ADD pytorch-pipeline /workspace/pytorch-pipeline

ENV PYTHONPATH /workspace/pytorch-pipeline

WORKDIR /workspace/pytorch-pipeline

#ENTRYPOINT /bin/bash
ENTRYPOINT ["python", "/workspace/pytorch-pipeline/training_task.py"]


