FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

ADD pytorch-pipeline /workspace/pytorch-pipeline

ENV PYTHONPATH /workspace/pytorch-pipeline

WORKDIR /workspace/pytorch-pipeline

ENTRYPOINT /bin/bash
