---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: SERVICE_NAME
    apptype: tf-serving
  name: SERVICE_NAME
  namespace: KUBEFLOW_NAMESPACE
spec:
  ports:
  - name: grpc-tf-serving
    port: 9000
    targetPort: 9000
  - name: tf-serving-builtin-http
    port: 8500
    targetPort: 8500
  selector:
    app: SERVICE_NAME
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: SERVICE_NAME
    apptype: tf-serving
  name: SERVICE_NAME
  namespace: KUBEFLOW_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME  
  template:
    metadata:
      labels:
        app: SERVICE_NAME
        version: v1
    spec:
      containers:
      - args:
        - --port=9000
        - --rest_api_port=8500
        - --model_name=MODEL_NAME
        - --model_base_path=MODEL_PATH
        command:
        - /usr/bin/tensorflow_model_server
        image: tensorflow/serving:2.3.0-rc0
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 9000
        name: MODEL_NAME
        ports:
        - containerPort: 9000
        - containerPort: 8500
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
